name: ShareX
title: ShareX - Screen capture, file sharing and productivity tool
description: ShareX is an open source program that lets you take screenshots or screencasts of any selected area with a single key, save them in your clipboard, hard disk or instantly upload them to over 80 different file hosting services.
url: https://getsharex.com
author: ShareX Team
github: https://github.com/ShareX/ShareX
twitter: GetShareX
markdown: kramdown

googleAnalyticsId: UA-40712139-3
addThisId: 53e2d1c30114f995

kramdown:
  input: GFM